[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
]

[profile.fuzz]
runs = 10000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[fmt]
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"

[rpc_endpoints]
bsc-test = "https://data-seed-prebsc-1-s1.binance.org:8545/"
bsc = "https://bsc-dataseed1.binance.org/"
local = "http://localhost:8545"
test = "${RPC_TEST}"
